### ISSUE TITLE
Next JS Project

### ISSUE THREAD

**Issue by babisha** [babisha/Capstone-Ecommerce-#1]
## OBJECTIVE : 

Create a new GitHub project for the capstone E-commerce task. With that, a new repository for the task has to be created and an initial commit has to be done. The Project has to be linked to the repository.

## Task Details:
Install Next JS in the project with proper dependencies. 
Create a new project and repository in GitHub and publish it.

**Comment by yogeshtakeo** [comment]
Babisha just divid the tasks properly and sub divide it

**Comment by yogeshtakeo** [comment]
Looks good on the division part babhisha.
