### ISSUE TITLE
Figma WireFrame

### ISSUE THREAD

**Issue by babisha** [babisha/Capstone-Ecommerce-#2]
1. Creating a homepage design with reusable components.
2.  Reusable components such as button : primary, secondary and tertiary buttons.
3. Designing a minimal Navigation in Header component as well as Footer component.

**Comment by babisha** [comment]
![Image](https://github.com/babisha/Capstone-Ecommerce-/assets/23157110/79f59487-78b7-4109-a7e8-7fa544b499ff)

**Comment by yogeshtakeo** [comment]
looking good babisha ❤️
